
CREATE TABLE eco_city (
    city_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE eco_category (
    category_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE eco_distribution_center (
    center_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE eco_client (
    client_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE eco_product (
    product_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(120)  NOT NULL UNIQUE,
    unit_price   NUMERIC(10,2) NOT NULL CHECK (unit_price > 0),
    category_id  INT NOT NULL,
    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id) REFERENCES eco_category (category_id)
);

CREATE TABLE eco_order (
    order_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code VARCHAR(20) NOT NULL UNIQUE,
    client_id  INT NOT NULL,
    city_id    INT NOT NULL,
    center_id  INT NOT NULL,
    order_date DATE NOT NULL,
    CONSTRAINT fk_order_client FOREIGN KEY (client_id) REFERENCES eco_client (client_id),
    CONSTRAINT fk_order_city   FOREIGN KEY (city_id)   REFERENCES eco_city (city_id),
    CONSTRAINT fk_order_center FOREIGN KEY (center_id) REFERENCES eco_distribution_center (center_id)
);

CREATE TABLE eco_order_detail (
    order_detail_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INT NOT NULL,
    product_id      INT NOT NULL,
    quantity        INT NOT NULL CHECK (quantity > 0),
    CONSTRAINT fk_detail_order   FOREIGN KEY (order_id)   REFERENCES eco_order (order_id),
    CONSTRAINT fk_detail_product FOREIGN KEY (product_id) REFERENCES eco_product (product_id),
    CONSTRAINT uq_order_product  UNIQUE (order_id, product_id)
);

CREATE TABLE eco_inventory (
    inventory_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   INT NOT NULL,
    center_id    INT NOT NULL,
    stock        INT NOT NULL CHECK (stock >= 0),
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES eco_product (product_id),
    CONSTRAINT fk_inventory_center  FOREIGN KEY (center_id)  REFERENCES eco_distribution_center (center_id),
    CONSTRAINT uq_product_center    UNIQUE (product_id, center_id)
);
